<?php
$allow_nonwebchat = false;

$saved = array();

// Open the database connection
require_once("opendb.php");
function getLevelArray($level) {
   global $saved;

   if (!array_key_exists($level, $saved)) {
      //NOW LEVRAGING THE POWER OF MYSQL
      $stripped = stripLevel($level);
      $query = pdo_prepare("(SELECT `display`, `game`, `type`, `qualify`, `gold`, `ultimate`, `standardiser`, `basescore`, `basemultiplier`, `goldbonus`, `platinumbonus`, `ultimatebonus`, `difficulty`, `golddifficulty`, `ultimatedifficulty`, `notes`, `disabled` FROM `levels` WHERE `stripped` = :stripped)" .
                           "UNION" .
                           "(SELECT `display`, `game`, `type`, `qualify`, `gold`, `ultimate`, `standardiser`, `basescore`, `basemultiplier`, `goldbonus`, `platinumbonus`, `ultimatebonus`, `difficulty`, `golddifficulty`, `ultimatedifficulty`, `notes`, `disabled` FROM `officiallevels` WHERE `stripped` = :stripped)");
      $query->bind(":stripped", $stripped);
      $result = $query->execute();

      if ($result->rowCount()) {
         $row = $result->fetchIdx();
         $saved[$level] =
                array("MissionName"        => $row[0],
                      "MissionGame"        => $row[1],
                      "MissionType"        => $row[2],
                      "QualifyTime"        => $row[3],
                      "GoldTime"           => $row[4],
                      "UltimateTime"       => $row[5],
                      "Standardiser"       => $row[6],
                      "BaseScore"          => $row[7],
                      "BaseMultiplier"     => $row[8],
                      "GoldBonus"          => $row[9],
                      "PlatinumBonus"      => $row[10],
                      "UltimateBonus"      => $row[11],
                      "Difficulty"         => $row[12],
                      "GoldDifficulty"     => $row[13],
                      "UltimateDifficulty" => $row[14],
                      "Notes"              => $row[15],
                      "Disabled"           => $row[16]);
      }
   }

   return $saved[$level];
}

function getRating($score, $level, $gametype, $modifiers = 0) {
   $mission = stripLevel($level);

   $data = getLevelArray($mission);
   if ($data == NULL)
      return -1;
   if ($data["Disabled"] == 1)
      return 0;

   // Get the factors pertaining to the given mission
   $type = $data["MissionType"];
   $game = $data["MissionGame"];

   if ($game == "MultiPlayer") {
      return 0;
   } else {
	   $time = $data["QualifyTime"];

	   if ($score < 100)
	      return -2; //Bad Score

	   // I just copied this all from 1.14
	   // No comments, just the guts <auto-generated>
	   $gold = $data["GoldTime"];
	   $ulti = $data["UltimateTime"];

	   $completion = 0;
	   if (strtolower($type) == "beginner")
	      $completion += ($game == "Ultra" ? 1500 : 1000);
	   if (strtolower($type) == "intermediate")
	      $completion += ($game == "Ultra" ? 2500 : 2000);
	   if (strtolower($type) == "advanced")
	      $completion += ($game == "Platinum" ? 3000 : 4000);
	   if (strtolower($type) == "expert")
	      $completion += 5000;
	   if (strtolower($type) == "lbcustom")
	      $completion += 4000;

      $bonus = 0;

      if ($gold && $score < $gold)
	      $bonus += ($data["PlatinumBonus"] ? $data["PlatinumBonus"] : $data["GoldBonus"]) * $data["GoldDifficulty"];
	   if ($ulti && $score < $ulti)
	      $bonus += $data["UltimateBonus"] * $data["UltimateDifficulty"];

      $completion *= $data["Difficulty"];

	   $standardiser = $data["Standardiser"];
	   $baseScore = $data["BaseScore"];
	   $multiplier = $data["BaseMultiplier"];

      $time = 0;
      if ($data["QualifyTime"] > 0)
         $time = min($score, $data["QualifyTime"]) / 1000;
      else
         $time = $score / 1000;

//(completion base score+(Platinum×platinum bonus)+(On Ult×platinum bonus)+(Ultimate×platinum bonus)+(Ultimate×ultimate bonus)+((LOG(Time,10)×Standardiser)−base score)×−1)×multiplier

	   // Spy47 : Awesome formula (not made by me).
	   $rating = ($completion + $bonus + (((log10($time) * $standardiser) - $baseScore) * -1)) * $multiplier;

      if ($score > $data["QualifyTime"] && ($data["QualifyTime"] > 0)) {
         //New ratings system, goooooooooooooo
         //=(completion base score + ((LOG(par score,10) * standardiser)-base score)*-1)*multiplier
         $parScore = ($completion + (((log10($data["QualifyTime"] / 1000) * $standardiser) - $baseScore) * -1)) * $multiplier;

         //=(par score-minimum score (1))/(5998.999-qualify time)
         $lostPerSec = ($parScore - 1) / (5998.999 - ($data["QualifyTime"] / 1000));

         //=MAX(time-par score, 0)
         $overPar = max($score - $data["QualifyTime"], 0) / 1000;

         // <rating> -= over par * lost per sec
         $rating -= $overPar * $lostPerSec;
      }

	   // Spy47 : They'll probably commit suicide if they see a negative rating.
	   $rating = floor($rating < 0 ? 0 : $rating);

	   return $rating;
	}
}
function getMissionList() {
   return array(
      "Trapdoors!",
      "WindingRoad",
      "TornadoBowl",
      "TimeTrial",
      "ThereandBackAgain",
      "PlatformParty",
      "MineField",
      "SuperBounce",
      "PlatformTraining",
      "ShockAbsorber",
      "GrandFinale",
      "Pitfalls",
      "MarbleMaterialsLab",
      "LearntheSuperSpeed",
      "LearntheSuperJump",
      "LearningtoRoll",
      "JumpTraining",
      "Gyrocopter",
      "GravityHelix",
      "Elevator",
      "CollecttheGems",
      "BumperTraining",
      "Breezeway",
      "AirMovement",
      "TheWave",
      "UpwardSpiral",
      "TriTwist",
      "Marbletris",
      "SpaceSlide",
      "TornadoAlley",
      "TaketheHighRoad",
      "GreatDivide",
      "SporkintheRoad",
      "SkatePark",
      "SkeeBallBonus",
      "RampMatrix",
      "ShockDrop",
      "Moto-Marblecross",
      "Hoops",
      "MarblePlayground",
      "MonsterSpeedwayQualifying",
      "MonsterSpeedway",
      "Jumpjumpjump",
      "HopSkipandaJump",
      "Gauntlet",
      "Half-Pipe",
      "GofortheGreen",
      "ForkintheRoad",
      "Twistingthenightaway",
      "WillO'TheWisp",
      "TotheMoon",
      "TrapDoorMadness",
      "Whirl",
      "TubeTreasure",
      "ThrillRide",
      "UnderConstruction",
      "FreewayCrossing",
      "Skyscraper",
      "Tightrope",
      "TowerMaze",
      "Pathways",
      "Three-FoldMaze",
      "SurvivaloftheFittest",
      "Tango",
      "PinballWizard",
      "SteppingStones",
      "Slip'nSlide",
      "Siege",
      "PointsoftheCompass",
      "SkiSlopes",
      "Shimmy",
      "Scaffold",
      "NaturalSelection",
      "Ordeal",
      "RampsReloaded",
      "ObstacleCourse",
      "Plumber'sPortal",
      "PipeDreams",
      "PathofLeastResistance",
      "GreatDivideRevisited",
      "KingoftheMountain",
      "MoneyTree",
      "Mudslide",
      "MoebiusStrip",
      "LeapofFaith",
      "Icarus",
      "Darwin'sDilemma",
      "A-Maze-ing",
      "HalfPipeElite",
      "Battlements",
      "Dive!",
      "FreeFall",
      "Daedalus",
      "Escher'sRace",
      "FanLift",
      "EyeoftheStorm",
      "Airwalk",
      "BlockParty",
      "AroundtheWorldin30seconds",
      "Acrobat",
      "TrainingTowers",
      "TeleportTraining",
      "RecoilTraining",
      "Ramps",
      "MagnetTraining",
      "MiniMountain",
      "LearnTheTimeModifier",
      "Let'sRoll!",
      "LearnTheWall-Hit",
      "KingOfTheMarble",
      "HazardLoop",
      "LearnTheRandomForce",
      "LearnTheFriction",
      "LearnTheEdgeHit",
      "LearnTheBouncyFloor",
      "GroundZero",
      "KeepOnRollin'",
      "JumpTutorial",
      "Battlecube",
      "FlightOfTheMarble",
      "GravityKnot",
      "DiagonalTraining",
      "DiamondRoundUp",
      "BusyBee",
      "BumpYourHead",
      "TimelyAscent",
      "WallMaster",
      "TripleDecker",
      "WindingSteps",
      "SkillZone",
      "Technoropes",
      "TakeAStroll",
      "RampMadness",
      "Sprint",
      "SpinPractice",
      "RollLikeTheWind",
      "PowerupPractice",
      "PuzzleOrdeal",
      "Perplexingness",
      "DownhillRacing",
      "MiniMarbleGolf",
      "MountaintopRetreat",
      "Gym",
      "MarbleAgilityCourse",
      "DaedalHelix",
      "BattlecubeRevisited",
      "MedievalMaze",
      "MarbleMiniGolfIcichole",
      "LoopExits",
      "DraggedUp!",
      "FloorClimb",
      "Divergence",
      "DoubleLoopLoop",
      "CycloneLaunch",
      "ByzantineHelix",
      "ConvolutedHelix",
      "BumpyHighway",
      "BasicAgilityCourse",
      "AvoidingHazards",
      "Astroflight",
      "PlatformRace",
      "NukeField",
      "Swivel",
      "Treachery",
      "SlopeMadness",
      "PinkFoldMaze",
      "SlipperySteps",
      "OrangeFoldMaze",
      "Nukesweeper",
      "NeonTech",
      "LightningIce",
      "FightingSlopes",
      "GapAimer",
      "DiamondSeekingFun",
      "CrashCourse",
      "xmastree",
      "walkinpark",
      "volcanicchasm",
      "TrickyTreehouse",
      "TowerMovement",
      "stairway",
      "speedbounce",
      "spacebase",
      "RiverCourse",
      "PipeWorld",
      "Oversimplified",
      "Macarena",
      "Logistics",
      "GreatDividePIY2",
      "GreatDividePIY",
      "FunWithFriction",
      "dogleg",
      "customjoseph",
      "cleanroom",
      "6foldrace",
      "vortex",
      "tubetower",
      "Terrortower",
      "stunt",
      "skyhook",
      "scalethewalls",
      "purplegrid",
      "pitbowl",
      "pipenightmare",
      "parhelion",
      "marbleroom",
      "marblecourse",
      "greenbrick",
      "gravitational",
      "goingup",
      "ghost",
      "dangerzone",
      "bumpers",
      "TubularTwist",
      "StructuralSwirl",
      "SkyAscent",
      "SkillCourse3MBP",
      "rottower",
      "RandomItUp",
      "MountainousMeander",
      "ds",
      "DownhillLightning",
      "DangerousRoads",
      "ct",
      "baronofthesummit",
   );
}

?>
